apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: kube-prometheus-stack
    version: 40.x
    repo: https://prometheus-community.github.io/helm-charts
    namespace: monitoring
    valuesFile: ./values.yaml
    includeCRDs: false
