apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: cert-manager
    version: 1.9.1
    repo: https://prometheus-community.github.io/helm-charts
    namespace: cert-manager
    valuesFile: ./values.yaml
    includeCRDs: false
