apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argo-cd
spec:
  destination:
    name: ""
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  source:
    path: ""
    repoURL: "https://prometheus-community.github.io/helm-charts"
    targetRevision: 40.x
    chart: kube-prometheus-stack
    helm:
      valueFiles:
        - values.yaml
      values: |
        prometheusOperator:
          admissionWebhooks:
            failurePolicy: Ignore
      skipCrds: true
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
