apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: ingress-nginx
    version: 4.3.0
    repo: https://kubernetes.github.io/ingress-nginx
    namespace: ingress-nginx
    valuesFile: ./values.yaml
    includeCRDs: true

resources:
- namespace.yaml
