apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    name: ""
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  source:
    repoURL: https://github.com/tomberget/aks-sandbox.git
    path: ./apps/cert-manager
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=false
